-- Migration: Add Invitation Codes Table
-- This table allows therapists to generate invitation codes that couples can use to self-register

CREATE TABLE IF NOT EXISTS "Couples_invitation_codes" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE,
  therapist_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  used_at TIMESTAMPTZ,
  used_by_couple_id UUID REFERENCES "Couples_couples"(id) ON DELETE SET NULL,
  is_active BOOLEAN DEFAULT TRUE
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_invitation_codes_code ON "Couples_invitation_codes"(code);
CREATE INDEX IF NOT EXISTS idx_invitation_codes_therapist ON "Couples_invitation_codes"(therapist_id);
CREATE INDEX IF NOT EXISTS idx_invitation_codes_active ON "Couples_invitation_codes"(is_active) WHERE is_active = TRUE;

-- RLS Policies for Invitation Codes
ALTER TABLE "Couples_invitation_codes" ENABLE ROW LEVEL SECURITY;

-- Therapists can view their own invitation codes
CREATE POLICY "Therapists can view own codes"
  ON "Couples_invitation_codes"
  FOR SELECT
  USING (
    therapist_id = auth.uid()
  );

-- Therapists can create invitation codes
CREATE POLICY "Therapists can create codes"
  ON "Couples_invitation_codes"
  FOR INSERT
  WITH CHECK (
    therapist_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM "Couples_profiles"
      WHERE id = auth.uid() AND role = 'therapist'
    )
  );

-- NOTE: Removed public SELECT policy for security
-- Invitation code validation is handled server-side via API endpoint

COMMENT ON TABLE "Couples_invitation_codes" IS 'Invitation codes generated by therapists for couple onboarding';
